let x = 10;
let y = 20;
let suma = x + y;
console.log("La suma es: ");
console.log(suma);
x = x + 1;
console.log("x incrementado: ");
console.log(x);
let resultado = x * 2 + y / 2;
console.log("Resultado complejo: ");
console.log(resultado);
